package products

// generated by pgtalk-gen on 2021-08-20 09:16:40.471032 &#43;0200 CEST m=&#43;0.025121000
// DO NOT EDIT

import (
	"bytes"
	"context"
	"fmt"
	"github.com/emicklei/pgtalk"
	"github.com/jackc/pgx/v4"
	"time"
)

var (
	_         = time.Now()
	tableInfo = pgtalk.TableInfo{Schema: "public", Name: "products", Alias: "p1"}
)

type Product struct {
	ID         *int64     // bigint
	CreatedAt  *time.Time // timestamp with time zone
	UpdatedAt  *time.Time // timestamp with time zone
	DeletedAt  *time.Time // timestamp with time zone
	Code       *string    // text
	Price      *int64     // bigint
	CategoryId *int64     // bigint
}

var (
	ID = pgtalk.NewInt64Access(pgtalk.MakeColumnInfo(tableInfo, "id", true, true, 1),
		func(dest interface{}, v *int64) { dest.(*Product).ID = v })
	CreatedAt = pgtalk.NewTimeAccess(pgtalk.MakeColumnInfo(tableInfo, "created_at", false, false, 2),
		func(dest interface{}, v *time.Time) { dest.(*Product).CreatedAt = v })
	UpdatedAt = pgtalk.NewTimeAccess(pgtalk.MakeColumnInfo(tableInfo, "updated_at", false, false, 3),
		func(dest interface{}, v *time.Time) { dest.(*Product).UpdatedAt = v })
	DeletedAt = pgtalk.NewTimeAccess(pgtalk.MakeColumnInfo(tableInfo, "deleted_at", false, false, 4),
		func(dest interface{}, v *time.Time) { dest.(*Product).DeletedAt = v })
	Code = pgtalk.NewTextAccess(pgtalk.MakeColumnInfo(tableInfo, "code", false, false, 5),
		func(dest interface{}, v *string) { dest.(*Product).Code = v })
	Price = pgtalk.NewInt64Access(pgtalk.MakeColumnInfo(tableInfo, "price", false, false, 6),
		func(dest interface{}, v *int64) { dest.(*Product).Price = v })
	CategoryId = pgtalk.NewInt64Access(pgtalk.MakeColumnInfo(tableInfo, "category_id", false, false, 7),
		func(dest interface{}, v *int64) { dest.(*Product).CategoryId = v })
	tableAccess = pgtalk.TableAccessor{TableInfo: tableInfo,
		Factory: func() interface{} { return new(Product) }, AllColumns: []pgtalk.ColumnAccessor{ID, CreatedAt, UpdatedAt, DeletedAt, Code, Price, CategoryId}}
)

// ColumnUpdatesFrom returns the list of changes to a Product for which updates need to be processed.
// Cannot be used to set null values for columns.
func ColumnUpdatesFrom(e Product) (list []pgtalk.SQLExpression) {
	if e.ID != nil {
		list = append(list, ID.Set(*e.ID))
	}
	if e.CreatedAt != nil {
		list = append(list, CreatedAt.Set(*e.CreatedAt))
	}
	if e.UpdatedAt != nil {
		list = append(list, UpdatedAt.Set(*e.UpdatedAt))
	}
	if e.DeletedAt != nil {
		list = append(list, DeletedAt.Set(*e.DeletedAt))
	}
	if e.Code != nil {
		list = append(list, Code.Set(*e.Code))
	}
	if e.Price != nil {
		list = append(list, Price.Set(*e.Price))
	}
	if e.CategoryId != nil {
		list = append(list, CategoryId.Set(*e.CategoryId))
	}
	return
}

// Next returns the next *Product from the iterator data.
// Use err to check for failure.
func Next(it *pgtalk.ResultIterator) (e *Product, err error) {
	var each = new(Product)
	// first check for query error in case caller forgot
	if err = it.Err(); err != nil {
		return nil, err
	}
	err = it.Next(each)
	return each, err
}

// String returns the debug string for *Product with all non-nil field values.
func (e *Product) String() string {
	b := new(bytes.Buffer)
	fmt.Fprint(b, "products.Product{")
	if e.ID != nil {
		fmt.Fprintf(b, "ID:%v ", *e.ID)
	}
	if e.CreatedAt != nil {
		fmt.Fprintf(b, "CreatedAt:%v ", *e.CreatedAt)
	}
	if e.UpdatedAt != nil {
		fmt.Fprintf(b, "UpdatedAt:%v ", *e.UpdatedAt)
	}
	if e.DeletedAt != nil {
		fmt.Fprintf(b, "DeletedAt:%v ", *e.DeletedAt)
	}
	if e.Code != nil {
		fmt.Fprintf(b, "Code:%v ", *e.Code)
	}
	if e.Price != nil {
		fmt.Fprintf(b, "Price:%v ", *e.Price)
	}
	if e.CategoryId != nil {
		fmt.Fprintf(b, "CategoryId:%v ", *e.CategoryId)
	}
	fmt.Fprint(b, "}")
	return b.String()
}

// AllColumns returns the list of all column accessors for usage in e.g. Select.
func AllColumns() []pgtalk.ColumnAccessor {
	return tableAccess.AllColumns
}

// Select returns a new ProductsQuerySet for fetching column data.
func Select(cas ...pgtalk.ColumnAccessor) ProductsQuerySet {
	return ProductsQuerySet{pgtalk.MakeQuerySet(tableAccess, cas)}
}

// ProductsQuerySet can query for *Product values.
type ProductsQuerySet struct {
	pgtalk.QuerySet
}

func (s ProductsQuerySet) Unwrap() pgtalk.QuerySet { return s.QuerySet }

// Where returns a new QuerySet with WHERE clause.
func (s ProductsQuerySet) Where(condition pgtalk.SQLExpression) ProductsQuerySet {
	return ProductsQuerySet{QuerySet: s.QuerySet.Where(condition)}
}

// Limit returns a new QuerySet with the maximum number of results set.
func (s ProductsQuerySet) Limit(limit int) ProductsQuerySet {
	return ProductsQuerySet{QuerySet: s.QuerySet.Limit(limit)}
}

// GroupBy returns a new QuerySet with the GROUP BY clause.
func (s ProductsQuerySet) GroupBy(cas ...pgtalk.ColumnAccessor) ProductsQuerySet {
	return ProductsQuerySet{QuerySet: s.QuerySet.GroupBy(cas...)}
}

// Having returns a new QuerySet with the HAVING clause.
func (s ProductsQuerySet) Having(expr pgtalk.SQLExpression) ProductsQuerySet {
	return ProductsQuerySet{QuerySet: s.QuerySet.Having(expr)}
}

// OrderBy returns a new QuerySet with the ORDER BY clause.
func (s ProductsQuerySet) OrderBy(cas ...pgtalk.ColumnAccessor) ProductsQuerySet {
	return ProductsQuerySet{QuerySet: s.QuerySet.OrderBy(cas...)}
}

// Exec runs the query and returns the list of *Product.
func (s ProductsQuerySet) Exec(ctx context.Context, conn *pgx.Conn) (list []*Product, err error) {
	err = s.QuerySet.ExecWithAppender(ctx, conn, func(each interface{}) {
		list = append(list, each.(*Product))
	})
	return
}

// Insert creates a MutationSet for inserting data with zero or more columns.
func Insert(cas ...pgtalk.ColumnAccessor) pgtalk.MutationSet {
	return pgtalk.MakeMutationSet(tableAccess, cas, pgtalk.MutationInsert)
}

// Delete creates a MutationSet for deleting data.
func Delete() pgtalk.MutationSet {
	return pgtalk.MakeMutationSet(tableAccess, pgtalk.EmptyColumnAccessor, pgtalk.MutationDelete)
}

// Update creates a MutationSet to update zero or more columns.
func Update(cas ...pgtalk.ColumnAccessor) pgtalk.MutationSet {
	return pgtalk.MakeMutationSet(tableAccess, cas, pgtalk.MutationUpdate)
}
